"""update a add created and update time in table

Revision ID: 75ae3ab1ecf8
Revises: f2974f51546c
Create Date: 2024-08-12 08:56:51.107634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ae3ab1ecf8'
down_revision: Union[str, None] = 'f2974f51546c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
